$(document).ready(function() {
	
	var changeEn = document.querySelector(".italian");
	var changeStory = document.querySelector(".italianStory");
	
	$( "#inItalian" ).click(function() {

		changeEn.innerHTML = "Noi crediamo che il nostro cibo deve essere il più autentico come la nostra atmosfera. Collaboriamo con fornitori regionali del Pacifico nord-occidentale, come Cascade Natural, mercati contadini, Carlton Fattoria, da agricoltura biologica Società e aziende agricole locali valorizzando il loro attenzione alla sostenibilità. Abbiamo scelto attivamente carne di manzo e di maiale liberi da ormoni, da fonti locali da abbinare con le verdure stagionali. Ci rifiutiamo di utilizzare conservanti, glutammato monosodico, e coloranti alimentari. Infine riteniamo che l'autenticità inizia in casa, dove abbiamo scelto ingredienti freschi per le nostre ricette e salse, in quanto riteniamo che la migliore qualità del nostro cibo spetta al rispetto per gli ingredienti migliori.";
		changeStory.innerHTML = "Ristorante Roma è modellato sul modello trattoria italiana, dove l'atmosfera è formale, ed il servizio è eccellente, e una clientela stabile è più importante di un'alta cucina. I piatti sono modesti focalizzati sulle regioni e sono serviti in abbondanza. Ci sforziamo di presentare vera cucina italiana nella sua forma più autentica con doni della terra e del mare, rompendo anche pregiudizi creati dalla cucina italiana-americanizzata. Lo Chef ed il proprietario Alex Petrache utilizza ricette che ha imparato mentre lavorava a Roma da oltre 17 anni come cuoco e chef che serve gli individui come Ricky Tognazzi, Raoul Bova, Sabrina Ferilli, Simona Izzo, Andrea Gaspari, Tinto Brass, Luca Barbareschi, Pamela Prati, e Asia Argento. Ci piace fare uso di ingredienti locali di stagione quando prepariamo i nostri sughi quotidiani fatti a mano, rendere il nostro Tiramisù e Panna Cotta. Il Ristorante Roma è una piccola struttura, basata nell'attenzione sulle relazioni e ripetere clientela ci si riempiono velocemente e raccomandare la prenotazione.";
	});

	$( "#inEnglish").click(function() {
		changeEn.innerHTML = "We believe that our food should be as authentic as our atmosphere. We partner with regional providers of the Pacific Northwest such as Cascade Natural, Farmer’s Markets, Carlton Farm, Organically Grown Company, and local farms valuing their focus on sustainability. We actively choose hormone and antibiotic free beef and pork from local sources to pair with seasonally farmed vegetables. We refuse to use preservatives, MSG, and food coloring. Finally we believe that authenticity starts at home where we choose fresh ingredients for our recipes and sauces, as we believe that the best quality of our food rests with the respect for the best ingredients.";
		changeStory.innerHTML = "Ristorante Roma is modeled after the Italian trattoria model of dining where the atmosphere is formal, the service is excellent, and a steady clientele is more important than haute cuisine. The dishes are modest with a regional focus and are served in plenty. We strive to present true Italian dining in its most authentic form using bounties of the land and sea while also breaking misconceptions created by Italian-Americanized cuisine. Chef and owner Alex Petrache uses recipes he learned while working in Rome for over 17 years as a cook and chef serving individuals such as Ricky Tognazzi, Raoul Bova, Sabrina Ferilli, Simona Izzo, Andrea Gaspari, Tinto Brass, Luca Barbareschi, Pamela Prati, and Asia Argento. We enjoy making use of seasonal local ingredients when we make our sauces daily and hand make our Tiramisù and Panna Cotta. Ristorante Roma is a small establishment and because of our focus on rapport and repeat clientele we fill up quickly and recommend a reservation.";
	});
	
});